### PR TITLE
Fix onError: frame comes from backend instead of string.

### PR DESCRIPTION
**Pull request by uladzimir-shelhunou**
@devsullo, could you please review?

### CODE REVIEW

**Comment by vvsh** [comment]
@devsullo, could you please review?

**Comment by uladzimir-shelhunou** [comment]
@devsullo, also, could you say how do you build the project? I see "Cannot find module 'stompjs'" and "Cannot find module 'sockjs'", when I added them to dependencies

**Comment by devsullo** [comment]
@vvsh I will review thank you!! I am using ionic2 framework and command `ionic serve` builds it form me. I will update documentation for building process.

**Comment by uladzimir-shelhunou** [comment]
@devsullo, you are welcome.

If you push my fix to npmjs, I will not need to build it :)

**Comment by uladzimir-shelhunou** [comment]
@devsullo, BTW, are you planning to wrap this library in Observable somehow?

**Comment by uladzimir-shelhunou** [comment]
>> I am using ionic2 framework and command ionic serve builds it form me.

My issue is that I used stompjs and sockjs-client but not @types/...

**Comment by uladzimir-shelhunou** [comment]
@devsullo, I also added default values for config options. I faced the issue, that if headers parameter is not specified, the library is failing with an error. The similar issue with heartbeats, if I do not specify heartbeats, then request to service is the following:

["CONNECT\naccept-version:1.1,1.0\nheart-beat:,\n\n\u0000"]

Where heartbeat value is empty and server responds with:

a["ERROR\nmessage:For input string\\c \"\"\ncontent-length:0\n\n\u0000"]

**Comment by devsullo** [comment]
@vvsh Do you find solution for "Cannot find module 'stompjs'" and "Cannot find module 'sockjs'" ? I will merge your request, just want to find, fix and test all issues

**Comment by devsullo** [comment]
@vvsh I found solution to **load modules**  in new version of angular CLI  in `typings.d.ts` add this

```
declare module 'stompjs';
declare module 'sockjs-client';
```

**Comment by uladzimir-shelhunou** [comment]
@devsullo, I just add them to dependencies in package.json.

Also you told about ionic, but I do not see the configuration file in the repo.

**Comment by devsullo** [comment]
@vvsh this is only angular2 service.. not demo or something. I think it must be clear and must be adjusted any new versions of angular2 and ionic2.. now to implement it in ionic2 and also in pure angular2 have not any problems

**Comment by devsullo** [comment]
@vvsh As for "frame comes from backend" I was using old version of sockjs-client and that why i missed It.. I will check it  soon

**Comment by uladzimir-shelhunou** [comment]
@devsullo, fantastic, thank you!

**Comment by devsullo** [comment]
@vvsh I tested 'frame' error in new version of stompjs and no such problem what you specified.. Do you use new versions of stompjs and sockjs_client?

**Comment by uladzimir-shelhunou** [comment]
@devsullo:

@types/sockjs-client: ^1.0.30
@types/stompjs: ^2.3.0

**Pull request merged**
